### ISSUE TITLE
Error Uncaught SyntaxError: Unexpected token ','

### ISSUE THREAD

**Issue by MacSass** [mathe1/WhatsAppOnlineTracker#1]
Hi,
nice script / extension - learned a lot from it. Especially I like how you add to the online status the updated information.

I think there is a small bug in the current version, at least I do get an error message when running it:
`Uncaught SyntaxError: Unexpected token ','  in tracker.js:253 `

Looking at the code I do think there is a closing bracket missing for the if statement in line 149.
Inserting a "}" after line 166 seems to fix the code for me.

I think storing times when you shortly switch a user would be a nice enhancement.

Regards - MacSass

**Comment by mathe1** [comment]
Okay, I upload the next version 1.6
It should fixed there.

> I think storing times when you shortly switch a user would be a nice enhancement.
That was an idea, but not so priority for me. But I will not forget it.
