### ISSUE TITLE
Getting rid of warning about CORS when using web logging ...

### ISSUE THREAD

**Issue by MacSass** [mathe1/WhatsAppOnlineTracker#2]
Hi,
the warning you see when using web-logging is caused by the fact that the script tries to make a request from 
https://web.whatsapp.com, which is a different site then the ressource requested.
This is a security measure to prevent cross-site-scripting attacks. 

While the script still seems to work, you can easily get rid of the warning if you modify the index.php script, allowing the access for https://web.whatsapp.com. So just add one line in the beginning to the index.php:

`<?php header('Access-Control-Allow-Origin: https://web.whatsapp.com'); ?>`

Regards - MacSass

**Comment by mathe1** [comment]
Hi, thanks for this useful hint.
I'll update the index.php
