### ISSUE TITLE
Error since version 1.6: DOMException

### ISSUE THREAD

**Issue by MacSass** [mathe1/WhatsAppOnlineTracker#3]
Hi,
since version 1.6 I´m getting two errors when status changes:
GET chrome-extension://invalid/ net::ERR_FAILED      chrome-extension://invalid/:1
Uncaught (in promise) DOMException: Failed to load because no supported source was found.    (index):1 

Can´t pinpoint the source of the issue right now as there is no reference to a line in the script ... I´m seeing this error each time the user comes online or goes offline ...

As far as I can see status updates to developer console are working, logging to external webserver is working, Updates to the status in topline every second is working.
So I suspect it has to do with some of the new functionality of monitoring messages (the monitored account has last send a message to me, not me to him).

**Comment by MacSass** [comment]
I took another look - it **_might_** be related to the line for playing audio:

`let url = 'chrome-extension://'+extsrc+'/audios/'+status+'.mp3'; `

Not sure - but maybe there is an audio missing? Did not have time yet to do extensive research ...

**Comment by MacSass** [comment]
I´m sorry - I reloaded Chrome and the extension and it is working now ... looks like the issue was on my side - whatever was causing it ...
Sorry for the confusion - I do better checking next time, issue can be closed ...

**Comment by mathe1** [comment]
> I took another look - it **_might_** be related to the line for playing audio:
> 
> `let url = 'chrome-extension://'+extsrc+'/audios/'+status+'.mp3'; `
> 
> Not sure - but maybe there is an audio missing? Did not have time yet to do extensive research ...

If you miss an audio, check your audios folder inside the extension folder.
The wished audio is definded in "status" variable.
In v1.6 we have these 5 possible status-names: alert, note, offline, online, writing

It is required to have these named audio files inside the "audios"-folder, but you may replace the files to your own wished sounds ;-)

**Comment by MacSass** [comment]
Just to let you know, there was no audio file missing - I tried again ... looks like it happens when you load the extension first time and then go the whatsapp desktop ... you have to restart Chrome after loading the extension, then it is working with no error.
Looks like the extension URL does not work before restarting Chrome ...

**Comment by mathe1** [comment]
Okay, thanks for your hint. 
I use the new MS Edge since it is based on Chromium.
