### ISSUE TITLE
Class names need updating ...

### ISSUE THREAD

**Issue by MacSass** [mathe1/WhatsAppOnlineTracker#4]
Hi, 
looks like WA desktop has a new release 2.2047.10 with changes class names, the extension does not work anymore right now.

Think the class names need to be updated.

Regards - MacSass

**Comment by mathe1** [comment]
Hi, thanks for reporting.

I reload the page.. - at my place it is still version 2.2045.19; I will looking forward to the new version and will fix it asap.

**Comment by mathe1** [comment]
Done, have fun!

**Comment by MacSass** [comment]
Nice! - Thanks!
