### ISSUE TITLE
Not working anymore since WA udpated

### ISSUE THREAD

**Issue by MacSass** [mathe1/WhatsAppOnlineTracker#5]
Hi,
looks like WA has updated it´s desktop site again, guess the element names have changed.

At least it is not working anymore since update to 2.2106.5.

Regards - MacSass

**Comment by mathe1** [comment]
Hi,
thanks for report.
I use it on my Raspi 24/7 without reload, so I don't recognize that. I will look at this...

**Comment by mathe1** [comment]
Okay, should be fixed.
Maybe the message-type classes could be still wrong - so pls tell me.

Have nice logging ;-)

**Comment by MacSass** [comment]
First look seems to be ok - but have not checked everything yet. Will let you know if I see anything strange.

I´m wondering how much effort it would be to "automate" those updates to figure out the classes whenever they change - not sure even if that would be possible - or worth the effort. After all WA does not update so often luckily ...

Thanks - MacSass

**Comment by mathe1** [comment]
Yes, I tought about this too.
The main layout does not change, but find out the classes for messages by automatic will be tricky, I think.

I will look for that near future what may possible. :D
